version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: bancodedados
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - db_network

volumes:
  db_data:


networks:
  db_network: